import html2canvas from 'html2canvas';
import { jsPDF } from 'jspdf';

export async function exportElementAsPdf(filename: string, element: HTMLElement) {
  // Render the element to a canvas
  const canvas = await html2canvas(element, { scale: 2, useCORS: true, backgroundColor: '#ffffff' });
  const imgData = canvas.toDataURL('image/png');

  // Create a PDF and add the image sized to fit
  const pdf = new jsPDF('p', 'pt', 'a4');
  const pdfWidth = pdf.internal.pageSize.getWidth();
  const pdfHeight = pdf.internal.pageSize.getHeight();

  const imgWidth = canvas.width;
  const imgHeight = canvas.height;
  const ratio = Math.min(pdfWidth / imgWidth, pdfHeight / imgHeight);
  const renderWidth = imgWidth * ratio;
  const renderHeight = imgHeight * ratio;

  const x = (pdfWidth - renderWidth) / 2;
  const y = 20; // small top margin

  pdf.addImage(imgData, 'PNG', x, y, renderWidth, renderHeight);
  pdf.save(filename);
}

export type InvoicePdfPayload = {
  invoiceNo: string;
  etrNo?: string;
  customerName: string;
  customerPin?: string;
  invoiceDate: string;
  dueDate: string;
  subtotal: number;
  excise: number;
  vat: number;
  total: number;
  currency?: string;
};

export function exportInvoicePdf(filename: string, payload: InvoicePdfPayload) {
  const pdf = new jsPDF('p', 'pt', 'a4');
  const pageWidth = pdf.internal.pageSize.getWidth();
  const margin = 40;
  const right = pageWidth - margin;
  const currency = payload.currency || "KES";
  const money = (value: number) => `${currency} ${Number(value || 0).toLocaleString()}`;
  const verification = `INV:${payload.invoiceNo}|ETR:${payload.etrNo || "-"}`;

  pdf.setFont("helvetica", "bold");
  pdf.setFontSize(18);
  pdf.text("Ayawin Enterprise ERP", margin, 52);
  pdf.setFont("helvetica", "normal");
  pdf.setFontSize(10);
  pdf.text("Nairobi, Kenya", margin, 68);
  pdf.text("PIN: P051999999Z", margin, 82);

  pdf.setFont("helvetica", "bold");
  pdf.setFontSize(15);
  pdf.text("TAX INVOICE", right, 52, { align: "right" });
  pdf.setFont("courier", "normal");
  pdf.setFontSize(10);
  pdf.text(payload.invoiceNo, right, 68, { align: "right" });
  pdf.setFont("helvetica", "normal");
  pdf.text(`ETR/TIMS: ${payload.etrNo || "-"}`, right, 82, { align: "right" });

  pdf.setDrawColor(220, 220, 220);
  pdf.line(margin, 94, right, 94);

  pdf.setFont("helvetica", "bold");
  pdf.text("Bill To", margin, 118);
  pdf.setFont("helvetica", "normal");
  pdf.text(payload.customerName, margin, 134);
  pdf.text(`KRA PIN: ${payload.customerPin || "-"}`, margin, 148);

  pdf.text(`Invoice Date: ${payload.invoiceDate}`, right, 118, { align: "right" });
  pdf.text(`Due Date: ${payload.dueDate}`, right, 134, { align: "right" });

  pdf.setDrawColor(235, 235, 235);
  pdf.setFillColor(248, 250, 252);
  pdf.rect(margin, 186, right - margin, 108, "F");
  pdf.setDrawColor(230, 230, 230);
  pdf.rect(margin, 186, right - margin, 108);

  const amountY = 214;
  pdf.setFont("helvetica", "normal");
  pdf.text("Subtotal", margin + 16, amountY);
  pdf.text(money(payload.subtotal), right - 16, amountY, { align: "right" });
  pdf.text("Excise Duty", margin + 16, amountY + 22);
  pdf.text(money(payload.excise), right - 16, amountY + 22, { align: "right" });
  pdf.text("VAT", margin + 16, amountY + 44);
  pdf.text(money(payload.vat), right - 16, amountY + 44, { align: "right" });
  pdf.setFont("helvetica", "bold");
  pdf.text("Total", margin + 16, amountY + 74);
  pdf.text(money(payload.total), right - 16, amountY + 74, { align: "right" });

  pdf.setDrawColor(220, 220, 220);
  pdf.line(margin, 330, right, 330);
  pdf.setFont("helvetica", "normal");
  pdf.setFontSize(9);
  pdf.text("Generated by Ayawin Enterprise ERP. This document is system generated.", margin, 348);
  pdf.text(`Verification: ${verification}`, margin, 362);

  pdf.save(filename);
}

export function exportReceiptPdf(
  filename: string,
  payload: InvoicePdfPayload & { paymentRef?: string; receivedFrom?: string },
) {
  const pdf = new jsPDF('p', 'pt', 'a4');
  const pageWidth = pdf.internal.pageSize.getWidth();
  const margin = 40;
  const right = pageWidth - margin;
  const currency = payload.currency || "KES";
  const money = (value: number) => `${currency} ${Number(value || 0).toLocaleString()}`;

  pdf.setFont("helvetica", "bold");
  pdf.setFontSize(18);
  pdf.text("Ayawin Enterprise ERP", margin, 52);
  pdf.setFont("helvetica", "normal");
  pdf.setFontSize(10);
  pdf.text("OFFICIAL PAYMENT RECEIPT", margin, 70);

  pdf.setFont("helvetica", "bold");
  pdf.setFontSize(12);
  pdf.text("Receipt", right, 52, { align: "right" });
  pdf.setFont("courier", "normal");
  pdf.text(`RCPT-${payload.invoiceNo}`, right, 70, { align: "right" });

  pdf.setDrawColor(220, 220, 220);
  pdf.line(margin, 86, right, 86);

  pdf.setFont("helvetica", "normal");
  pdf.text(`Received from: ${payload.receivedFrom || payload.customerName}`, margin, 112);
  pdf.text(`Reference invoice: ${payload.invoiceNo}`, margin, 130);
  pdf.text(`Payment reference: ${payload.paymentRef || payload.etrNo || "-"}`, margin, 148);
  pdf.text(`Receipt date: ${payload.invoiceDate}`, right, 112, { align: "right" });

  pdf.setFillColor(248, 250, 252);
  pdf.rect(margin, 188, right - margin, 72, "F");
  pdf.rect(margin, 188, right - margin, 72);
  pdf.setFont("helvetica", "bold");
  pdf.setFontSize(14);
  pdf.text("Amount Received", margin + 16, 216);
  pdf.text(money(payload.total), right - 16, 216, { align: "right" });
  pdf.setFont("helvetica", "normal");
  pdf.setFontSize(10);
  pdf.text(`Tax invoice total: ${money(payload.total)}`, margin + 16, 238);

  pdf.setDrawColor(220, 220, 220);
  pdf.line(margin, 330, right, 330);
  pdf.text("System generated receipt. Keep this for audit and reconciliation.", margin, 350);

  pdf.save(filename);
}

export function exportVerificationCertificatePdf(
  filename: string,
  payload: {
    invoiceNo: string;
    serverHash: string;
    verificationUrl: string;
    validationStatus: "valid" | "invalid" | "reference-only";
    generatedAt: string;
    verifiedBy?: string;
  },
) {
  const pdf = new jsPDF('p', 'pt', 'a4');
  const pageWidth = pdf.internal.pageSize.getWidth();
  const margin = 40;
  const right = pageWidth - margin;

  pdf.setFont("helvetica", "bold");
  pdf.setFontSize(18);
  pdf.text("Ayawin Enterprise ERP", margin, 52);
  pdf.setFontSize(14);
  pdf.text("Document Verification Certificate", margin, 74);

  pdf.setDrawColor(220, 220, 220);
  pdf.line(margin, 90, right, 90);

  pdf.setFont("helvetica", "normal");
  pdf.setFontSize(10);
  pdf.text(`Invoice number: ${payload.invoiceNo}`, margin, 116);
  pdf.text(`Verification status: ${payload.validationStatus}`, margin, 134);
  pdf.text(`Generated at: ${payload.generatedAt}`, margin, 152);
  if (payload.verifiedBy) {
    pdf.text(`Verified by: ${payload.verifiedBy}`, margin, 170);
  }

  pdf.setFont("helvetica", "bold");
  pdf.text("Server hash", margin, 204);
  pdf.setFont("courier", "normal");
  pdf.setFontSize(9);
  pdf.text(payload.serverHash, margin, 222, { maxWidth: right - margin });

  pdf.setFont("helvetica", "bold");
  pdf.setFontSize(10);
  pdf.text("Verification URL", margin, 270);
  pdf.setFont("helvetica", "normal");
  pdf.text(payload.verificationUrl, margin, 288, { maxWidth: right - margin });

  pdf.setFontSize(9);
  pdf.setTextColor(90, 90, 90);
  pdf.text(
    "This certificate confirms the verification result captured at generation time. Re-verify against live API if required.",
    margin,
    332,
    { maxWidth: right - margin },
  );

  pdf.save(filename);
}
