services:
  - type: web
    name: martin-enterprise-frontend
    runtime: static
    plan: free
    buildCommand: npm ci && npm run build
    staticPublishPath: .output/public
    pullRequestPreviewsEnabled: true
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_API_BASE
        sync: false
      - key: VITE_API_V1
        value: "true"
