const BCRYPT_ROUNDS = Number(process.env.BCRYPT_ROUNDS) || 12;
const PASSWORD_RESET_HOURS = Number(process.env.PASSWORD_RESET_HOURS) || 24;
const REFRESH_DAYS_DEFAULT = Number(process.env.JWT_REFRESH_EXPIRES_DAYS) || 7;
const REFRESH_DAYS_REMEMBER = Number(process.env.JWT_REFRESH_REMEMBER_DAYS) || 30;

module.exports = {
  BCRYPT_ROUNDS,
  PASSWORD_RESET_HOURS,
  REFRESH_DAYS_DEFAULT,
  REFRESH_DAYS_REMEMBER,
};
